spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    feign: WARN

cobis:
  url: "https://prod.example.com/v1"
  channel: "channelCcd"
  terminal: "consumer"
  api-key: "${COBIS_API_KEY}"
  timeout:
    connect: 5000
    read: 10000