spring:
  config:
    activate:
      on-profile: uat

  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - name: key-vault
              enabled: true
              endpoint: https://tecylab-key-jp.vault.azure.net/

logging:
  level:
    feign: INFO

cobis:
  url: "https://uat.example.com/v1"
  channel: "channelCcd"
  terminal: "consumer"
  api-key: "${COBIS_API_KEY}"
  timeout:
    connect: 8000
    read: 15000