spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    feign: DEBUG
    feign.client: DEBUG
    feign.Logger: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    pe.interbank.ccd.issued.device.admin.client.cobis: DEBUG

cobis:
  url: "https://dvi758vyde.execute-api.us-east-1.amazonaws.com/v1"
  channel: "channelCcd"
  terminal: "consumer"
  api-key: "${COBIS_API_KEY}"
  timeout:
    connect: 5000
    read: 10000