server:
  port: 8080

cobis:
  url: "https://dvi758vyde.execute-api.us-east-1.amazonaws.com/v1"
  channel : "channelCcd"
  terminal : "consumer"
  api-key : "${COBIS_API_KEY}" # variable de entorno , NUNCA quemada en c√≥digo
  timeout:
    connect: 5000
    read: 10000
