spring:
  config:
    activate:
      on-profile: uat

logging:
  level:
    feign: INFO

cobis:
  url: "https://uat.example.com/v1"
  channel: "channelCcd"
  terminal: "consumer"
  api-key: "${COBIS_API_KEY}"
  timeout:
    connect: 8000
    read: 15000