spring:
  config:
    activate:
      on-profile: dev

  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - name: key-vault
              enabled: true
              endpoint: https://tecylab-key-jp.vault.azure.net/


logging:
  level:
    feign: DEBUG
    feign.client: DEBUG
    feign.Logger: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    pe.interbank.ccd.issued.device.admin.client.cobis: DEBUG
    com.azure: DEBUG
    com.azure.identity: TRACE

cobis:
  url: "https://dvi758vyde.execute-api.us-east-1.amazonaws.com/v1"
  channel: "channelCcd"
  terminal: "consumer"
  api-key: "${ccd-secret-apigw-cobis-authentication-x-api-key}"
  timeout:
    connect: 5000
    read: 10000